version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
    networks:
      - cinema-network
      - net
    volumes:
      - cinema-redis-data:/usr/src/data

  redis-commander:
    container_name: 'redis-commander'
    image: 'ghcr.io/joeferner/redis-commander:latest'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    restart: always
    networks:
      - cinema-network
      - net
    depends_on:
      - redis

  api:
    container_name: cinema-api_app
    build:
      context: server
      target: prod
      dockerfile: Dockerfile
    volumes:
      - cinema-server:/usr/src/api
      - cinema-server-node-modules:/usr/src/api/node_modules
      - uploaded-files:/usr/src/api/uploads
#      - /Documents/cinema/uploads/:/usr/src/api/uploads
    env_file:
      - server/.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public&connect_timeout=300
    ports:
      - "4201:4200"
    networks:
      - cinema-network
      - net

  web:
    container_name: cinema-web_app
    tty: true
    build:
      context: web
      target: build
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      REACT_APP_UPLOADS_URL: ${REACT_APP_UPLOADS_URL}
      UPLOAD_HOST: ${UPLOAD_HOST}
      REACT_APP_DOCKER_URL: ${REACT_APP_DOCKER_URL}
      REACT_APP_ENV: ${REACT_APP_ENV}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
#      - VIRTUAL_HOST=cinema.ilyasizov.webtm.ru
#      - VIRTUAL_PORT=3001
#      - LETSENCRYPT_HOST=cinema.ilyasizov.webtm.ru
#      - LETSENCRYPT_EMAIL=user@domain.com
    volumes:
      - cinema-web:/usr/src/app
      - cinema-web-node-modules:/usr/src/app/node_modules
      - uploaded-files:/usr/src/app/uploads
    ports:
      - "3001:3000"
    networks:
      - cinema-network
      - net
#    extra_hosts:
#      - host.docker.internal:host-gateway
#    depends_on:
#      - api
#    links:
#      - api

volumes:
  cinema-server:
  cinema-web:
  uploaded-files:
  redis-data:
  cinema-web-node-modules: null
  cinema-server-node-modules: null

networks:
  cinema-network:
    driver: bridge
  net:
    external: true

