version: '3.9'

services:
  api:
    container_name: cinema-api_app
    build:
      context: server
      target: prod
      dockerfile: Dockerfile
    volumes:
      - cinema-server:/usr/src/api
      - cinema-server-node-modules:/usr/src/api/node_modules
      - uploaded-files:/usr/src/api/uploads
#      - /Documents/cinema/uploads/:/usr/src/api/uploads
    env_file:
      - server/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public&connect_timeout=300
    ports:
      - 4201:4201
    networks:
      - cinema-network
#    extra_hosts:
#      - host.docker.internal:host-gateway

  web:
    container_name: cinema-web_app
    tty: true
    build:
      context: web
      target: build
      dockerfile: Dockerfile
    env_file:
      - web/.env
    environment:
      - VIRTUAL_HOST=cinema.ilyasizov.webtm.ru
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=cinema.ilyasizov.webtm.ru
      - LETSENCRYPT_EMAIL=user@domain.com
    volumes:
      - cinema-web:/usr/src/app
      - cinema-web-node-modules:/usr/src/app/node_modules
      - uploaded-files:/usr/src/app/uploads
    ports:
      - 3001:3001
    networks:
      - cinema-network
      - net
#    extra_hosts:
#      - host.docker.internal:host-gateway
    depends_on:
      - api
    links:
      - api

volumes:
  cinema-server:
  cinema-web:
  uploaded-files:
  cinema-web-node-modules: null
  cinema-server-node-modules: null

networks:
  cinema-network:
    driver: bridge
  net:
    external: true

